/*This example draws voronoi diagram generated by a random set of points.*/
String fileName;
void setup() {
 size(600,600,P3D); //size of your intended pattern
 noLoop(); // don't need to use the draw loop
 
 /*unique name for your file. if left unchanged,
 will simply save file with current milisecond*/
 fileName= "voronoi"+millis()+".pdf";
  
  beginRaw(PDF, fileName); //enables you to save your design to a pdf
  
   
   setupVoronoi(); // create your voronoi generator
 
     int pointNum =50; //number of total points
     
   for (int i=0;i<pointNum;i++){
      float x = random(0,width);
      float y= random(0,height);
       voronoi.addPoint(new Vec2D(x,y));
  }
    drawVoronoi(); //renders your voronoi
   endRaw(); //ends the recording
 

}
