/*This example draws voronoi diagram generated by a random set of points.*/

void setup() {
 size(600,600,P3D); //size of your intended pattern
 noLoop(); // don't need to use the draw loop
 
 /*unique name for your file. if left unchanged,
 will simply save file with current milisecond*/
 String fileName= "voronoi"+millis()+".pdf";
  
  beginRaw(PDF, fileName); //enables you to save your design to a pdf
  
   
   setupVoronoi(); // create your voronoi generator
 
   int pointNum =25; //number of total points
   
    //generates a regular grid of pointNum x pointNum of points 
  for (int i=0;i<pointNum+1;i++){
     for (int j=0;j<pointNum+1;j++){
    
       float xCoord = width/pointNum*(i);
       float yCoord = height/pointNum*(j);
       voronoi.addPoint(new Vec2D(xCoord,yCoord));
     }
  }
  
  
  //uncomment this code to draw 4 corner points and one center point
  int cornerCenter=4;
  
   voronoi.addPoint(new Vec2D(width/2, height/2)); // adds a new point to your voronoi generator
   voronoi.addPoint(new Vec2D(width/cornerCenter, height/cornerCenter)); 
   voronoi.addPoint(new Vec2D(width-width/cornerCenter, height/cornerCenter));
   voronoi.addPoint(new Vec2D(width-width/cornerCenter, height-height/cornerCenter));
   voronoi.addPoint(new Vec2D(width/cornerCenter, height-height/cornerCenter));
   
   
   
   drawVoronoi(); //renders your voronoi
   endRaw(); //ends the recording
 

}







